// FOR ALL TASKS
export const GET_ALL_TASKS = 'GET_ALL_TASKS'
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS'
export const GET_ALL_TASKS_FAIL = 'GET_ALL_TASKS_FAIL'
// export const GET_ALL_TASKS_DELETED = 'GET_ALL_TASKS_DELETED'


// SELECT A TASK
export const GET_SINGLE_TASK = 'GET_SINGLE_TASK'
export const GET_SINGLE_TASK_SUCCESS = 'GET_SINGLE_TASK_SUCCESS'
export const GET_SINGLE_TASK_FAIL = 'GET_SINGLE_TASK_FAIL'
// export const GET_SINGLE_TASK_DELETED = 'GET_SINGLE_TASK_DELETED'


// CREATE A TASK
export const ADD_A_TASK = 'ADD_A_TASK'
export const ADD_A_TASK_SUCCESS = 'ADD_A_TASK_SUCCESS'
export const ADD_A_TASK_FAIL = 'ADD_A_TASK_FAIL'


// UPDATE A TASK
export const UPDATE_A_TASK = 'UPDATE_A_TASK'
export const UPDATE_A_TASK_SUCCESS = 'UPDATE_A_TASK_SUCCESS'
export const UPDATE_A_TASK_FAIL = 'UPDATE_A_TASK_FAIL'


// DELETE A TASK
export const DELETE_A_TASK = 'DELETE_A_TASK'
export const DELETE_A_TASK_SUCCESS = 'DELETE_A_TASK_SUCCESS'
export const DELETE_A_TASK_FAIL = 'DELETE_A_TASK_FAIL'




